---
- name: install tomcat
  become: yes
  hosts: appserver
  vars:
    tomcat_home_dir: /opt/tomcat
    tomcat_user: tomcat
    tomcat_default_shell: /bin/false
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.88/bin/apache-tomcat-9.0.88.tar.gz
    tomcat_download_path: /tmp/apache-tomcat-9.0.88.tar.gz
    tomcat_users_location: /opt/tomcat/latest/conf/tomcat-users.xml
    tomcat_manager_conf_location: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
    tomcat_hostmanager_conf_location: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
  tasks:
    - name: install java
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present
        update_cache: yes
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_user }}"
        shell: "{{ tomcat_default_shell }}"
        create_home: true
        home: "{{ tomcat_home_dir }}"
    - name: download tomcat tar file
      ansible.builtin.get_url:
        url: "{{ tomcat_url }}"
        dest: "{{ tomcat_download_path }}"
    - name: unarchive tomcat zip file 
      ansible.builtin.unarchive:
        src: "{{ tomcat_download_path }}"
        dest: "{{ tomcat_home_dir }}"
        remote_src: yes
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "{{ tomcat_home_dir }}/apache-tomcat-9.0.88"
        dest: "{{ tomcat_home_dir }}/latest"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        state: link
    - name:  Change the directory ownership
      ansible.builtin.file:
        path: "{{ tomcat_home_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
    - name: making shell scripts inside the Tomcat is excutable 
      ansible.builtin.file:
        path: "{{ item }}"
        
        mode: u+x,g+x,o+x
      with_fileglob:
        - "/opt/tomcat/latest/bin/*.sh"
    - name: copy the tomcat service unit file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        
    - name: enable tomcat and start the service
      ansible.builtin.service:
        name: tomcat
        daemon_reload: yes
        enabled: yes
        state: started
    - name: copy the tomcat users xml
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: "{{ tomcat_users_location }}"
    - name: copy manager context xml
      ansible.builtin.copy:
        src: manager-context.xml
        dest: "{{ tomcat_manager_conf_location }}"
    - name: copy host manager context xml
      ansible.builtin.copy:
        src: hostmanager-context.xml
        dest: "{{ tomcat_hostmanager_conf_location }}"
    - name: restart tomcat service
      ansible.builtin.service:
        name: tomcat
        state: restarted
        