---
- name: install tomcat
  become: yes
  hosts: appserver
  vars:
    tomcat_home_dir: /opt/tomcat
    tomcat_user: tomcat
    tomcat_default_shell: /bin/false
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.0-M19/bin/apache-tomcat-11.0.0-M19.tar.gz
    tomcat_download_path: /tmp/apache-tomcat-11.0.0-M19.tar.gz
  tasks:
    - name: install java
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present
        update_cache: yes
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        shell: "{{ tomcat_default_shell }}"
        create_home: true
        home: "{{ tomcat_home_dir }}"
    - name: download tomcat tar file
      ansible.builtin.get_url:
        url: "{{ tomcat_url }}"
        dest: "{{ tomcat_download_path }}"
    - name: unarchive tomcat zip file 
      ansible.builtin.unarchive:
        src: "{{ tomcat_download_path }}"
        dest: "{{ tomcat_home_dir }}"
        remote_src: yes
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "{{ tomcat_home_dir }}/apache-tomcat-11.0.0-M19"
        dest: "{{ tomcat_home_dir }}/latest"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        state: link
    - name:  Change the directory ownership
      ansible.builtin.file:
        path: "{{ tomcat_home_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
    - name: making shell scripts inside the Tomcat is excutable 
      ansible.builtin.file:
        path: '/opt/tomcat/latest/bin/*.sh'
        state: file
        mode: u+x,g+x,o+x
    - name: create a unit file  
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/tomcat.service
        line: '[Unit]
               Description=Tomcat 9 servlet container
               After=network.target

               [Service]
               Type=forking

               User=tomcat
               Group=tomcat

               Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
               Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"

               Environment="CATALINA_BASE=/opt/tomcat/latest"
               Environment="CATALINA_HOME=/opt/tomcat/latest"
               Environment="CATALINA_PID=/opt/tomcat/latest/temp/tomcat.pid"
               Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

               ExecStart=/opt/tomcat/latest/bin/startup.sh
               ExecStop=/opt/tomcat/latest/bin/shutdown.sh

               [Install]
               WantedBy=multi-user.target'

        create: yes
        state: present