---
- name: game of life
  become: yes
  hosts: all
  tasks:
    - name: install java 8
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: install tomcat 9
      ansible.builtin.apt:
        name: tomcat9
        state: present
    - name: download game of life war file to webapps
      ansible.builtin.get_url:
        url: https://dockerimages1.s3.ap-south-1.amazonaws.com/gameoflife.war
        dest: /var/lib/tomcat9/webapps/
    - name: restart tomcat service 
      ansible.builtin.service:
        name: tomcat9
        enabled: yes
        state: restarted
        